Working external keymaps

diff --git a/functions/filter-select b/functions/filter-select
--- a/functions/filter-select
+++ b/functions/filter-select
@@ -133,6 +133,7 @@ function filter-select() {
     local selected_index mark_idx_disp hi start end spec
     local desc desc_num desc_disp bounds
 
+    local -a external_keymaps
     local -a displays matched_desc_keys match mbegin mend outs exit_wigdets
     local -a init_region_highlight marked_lines
     local -A candidates descriptions matched_descs
@@ -161,7 +162,7 @@ function filter-select() {
     descriptions=()
     exit_wigdets=(accept-line accept-search send-break)
 
-    while getopts 't:A:d:D:nrme:s:k:i' opt; do
+    while getopts 't:A:d:D:nrme:s:M:ki' opt; do
         case "${opt}" in
             t)
                 title="${OPTARG}"
@@ -199,6 +200,11 @@ function filter-select() {
             s)
                 initbuffer="${OPTARG}"
                 ;;
+            M)
+                # Allow widgets to apply additional keymaps
+                external_keymaps+="${OPTARG}"
+                ;;
+
             k)
                 # If there are no matches, reply with the query text
                 keep_query_text=1
@@ -309,8 +315,16 @@ function filter-select() {
                 (( cursor_line = desc_num ))
                 ;;
 
-            self-insert|undefined-key)
+            self-insert)
+                echo "doing self-insert: ${key}" >> /tmp/zaw.log
                 LBUFFER="${LBUFFER}${key}"
+                _filter-select-reset
+                ;;
+
+            undefined-key)
+                #
+                echo "undefined-key: ${key}" >> /tmp/zaw.log
+                # LBUFFER="${LBUFFER}${key}"
                 _filter-select-reset
                 ;;
 
@@ -319,6 +333,7 @@ function filter-select() {
                 ;;
 
             *)
+                echo "anything? key: ${key} bounds: ${bounds}" >> /tmp/zaw.log
                 buffer_pre_zle="${BUFFER}"
 
                 zle "${bounds}"
@@ -449,6 +464,10 @@ function filter-select() {
                     if (( disp_num == cursor_line )); then
                         region_highlight+="${offset} $(( offset + ${#desc_disp} + 1 )) ${hi_selected}"
                         selected="${candidates[$i]}"
+
+                        typeset -g FILTER_SELECT_SELECTED
+                        FILTER_SELECT_SELECTED="${selected}"
+
                         (( selected_num = display_head_line + disp_num - 1 ))
                         selected_index="${i}"
                     fi
@@ -487,10 +506,41 @@ function filter-select() {
             break
         else
             key="${reply}"
-            # TODO: key sequence
-            outs=("${(z)$( bindkey -M filterselect -- "${key}" )}")
+            key_code_widget="undefined-key"
+
+            for kmap in "${(@)external_keymaps}"; do
+                # # return value: [ "KeyCode", "Widget" ]
+                # # e.g., "^?" backward-delete-char
+                outs=("${(z)$( bindkey -M $kmap -- "${key}" )}")
+                key_code="${outs[1]}"
+                key_code_widget="${outs[2]}"
+                [[ $? == 0 ]] && [[ $key_code_widget != "undefined-key" ]] && break
+            done
+
+            if [[ -z $key_code_widget ]] || [[ $key_code_widget == "undefined-key" ]]; then
+                # echo "none found in external, looking in filter select" >> /tmp/zaw.log
+                outs=("${(z)$( bindkey -M filterselect -- "${key}" )}")
+                key_code="${outs[1]}"
+                key_code_widget="${outs[2]}"
+            fi
+
+            if [[ $key_code_widget == "undefined-key" ]]; then
+                echo "keycode undefined: $key_code" >> /tmp/zaw.log
+            fi
+
+            # key_code=$(echo $key_code  | od -c)
+            key_code=$(echo $key_code  | tr -d '"')
+
+            # echo "keycode esape $(echo $key_code)" >> /tmp/zaw.log
+            # echo "keycode length: $(echo -n $key_code | wc -m)" >> /tmp/zaw.log
+            if [[ $key_code =~ "^.$" ]]; then
+                # echo "single key, setting to 'self-insert': $key_code" >> /tmp/zaw.log
+                key_code_widget=self-insert
+            fi
+
             # XXX: will $outs contains more than two values?
-            bounds="${outs[2]}"
+            bounds="$key_code_widget"
+            # unset key_code
         fi
     done
 
